# Generated by Django 3.0.8 on 2020-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201105_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(related_name='products', to='api.Product'),
        ),
    ]
