# Generated by Django 3.0.8 on 2020-11-26 13:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201126_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='response_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
